### ISSUE TITLE
rebuild tree from React VirtualDOM on every request

### ISSUE THREAD

**Issue by baruchvlz** [baruchvlz/resq#30]
Current implementation of the `resq$` and `resq$$` commands use only the first creation of the virtual dom. If the vdom ever changes, these changes are not reflected in the tree.

**Comment by lcharbon** [comment]
I'm having an issue where whenever I navigate with React Router resq throws:
```
index.js:244 Uncaught TypeError: Cannot read property 'children' of undefined
    at index.js:244
    at index.js:252
    at Array.forEach (<anonymous>)
    at d (index.js:237)
    at m.find (index.js:384)
    at i (index.js:410)
    at u (index.js:414)
    at <anonymous>:1:8
```
When querying for a component.

Minimal working example: https://github.com/lcharbon/webdriverio_bugs_demo/tree/router-bug

#### Steps to reproduce
1) Run `yarn start`.
2) Navigate to http://localhost:3000/home.
3) Click "Click Me" button.
4) Run `window.resq$("Success")` in browser console.

If this issue does not covers this, I will move this info to another issue.

**Comment by baruchvlz** [comment]
That might be because the tree the library builds from the VDOM doesn't get updated when the VDOM changes. I have a change for this [here](https://github.com/baruchvlz/resq/commit/1de87297bd907f0a63e0a28d1ada39b014d24865) but I haven't finished adding the tests and currently I'm busy with finalizing a project for work.

Hopefully I'll be able to finish this by the end of the week, along another feature for https://github.com/webdriverio/webdriverio/issues/3965

**Comment by lcharbon** [comment]
Just pulled the latest Webdriverio and the issue demonstrated in the [minimal example](https://github.com/lcharbon/webdriverio_bugs_demo/tree/router-bug) is still occurring.

Would you like me to create another issue for this?

**Comment by baruchvlz** [comment]
No need for another issue. I verified it and it happens even without WebdriverIO. It also seems to be something to do when mixing in React Router.

```js
(async () => {
  await waitToLoadReact(10000)
  const i = resq$("Button")
  i.node.click()

  setTimeout(async () => {
    resq$('Button').node.click()
  }, 3000)
})()
```

This will work if you're already inside `/success` but if you go from `/home` -> `/success` the error appears. I will take care of this during the week.

**Comment by baruchvlz** [comment]
Closing as it seems this has lost interest.

**Comment by lcharbon** [comment]
Lost interest?

**Comment by baruchvlz** [comment]
@lcharbon I thought since there was no traction on the issue that it had lost interest. I now see that I said I would take care of it. Sorry I forgot. 

If you still have this problem, please open a new issue and we'll look at it.

**Comment by baruchvlz** [comment]
Perfect. Thanks!
