### ISSUE TITLE
element.node is null

### ISSUE THREAD

**Issue by simo-eskalera** [baruchvlz/resq#33]
Recently came across an issue with our react app and webdriver.io returning elements without the underlying node. The node value is `null` as shown below:

<img width="556" alt="Screen Shot 2019-06-28 at 12 30 50 PM" src="https://user-images.githubusercontent.com/49319958/60539931-ef6a4200-9cdb-11e9-8616-07b8a7b69baf.png">

This seems to point to $resq. More details here:
https://github.com/webdriverio/webdriverio/issues/4129

Any ideas what could be the issue?

**Comment by simo-eskalera** [comment]
Can this issue get some love? :)

**Comment by christian-bromann** [comment]
@simo-eskalera of course, you are welcome to contribute!

**Comment by baruchvlz** [comment]
@simo-eskalera I'm on vacation right now. But as Christian said, if you can / want to take a look at it you're more than welcome (:

**Comment by baruchvlz** [comment]
Is there a way you can make a reproducible error in [stackblitz](https://stackblitz.com/edit/resq)?

**Comment by simo-eskalera** [comment]
Thanks @christian-bromann and @baruchvlz , I provided an update here: https://github.com/webdriverio/webdriverio/issues/4129
Basically, some wrapper components don't directly have node elements. I think this module does what it's supposed to do. and the issue is to figure out how I can traverse `UsernameField` > ... > `input`

**Comment by baruchvlz** [comment]
@simo-eskalera Could you verify if #37 fixes your issue?

**Comment by simo-eskalera** [comment]
Thanks @baruchvlz Yes, from looking at the PR, it does indeed iterate over the children collection to find a node that is not null.
