### ISSUE TITLE
Bunch of suggestions

### ISSUE THREAD

**Issue by bendtherules** [baruchvlz/resq#34]
I am not sure if creating separate issue for all of these makes sense, but these are roughly the concerns I have while looking through the code and underlying FiberNode structure -

1. No direct access to underlying FiberNode.
The output is a simplified structure (duplicated and subset), which might be great for common testing usecases. But it has lot of downsides.
Like:
a. Power users can't do something more interesting (like access the class instances, present in `stateNode`) with the simplified output (being subset).
b. It duplicates whole subtree (of FiberNode) into the simplified structure, which might be a complete waste if I only want to access the first node  (being duplicated).
c. You can't "resume" or chain search from the output of a previous search. For ex., resume means you can find a component from the first search and use the output to do a second search which is within the found component (being subset). To give a concrete example `document.querySelector("#outer").querySelector("#inner")`.
3. No proper CSS selector supported. Only some degree of nesting like `classA classB` is supported, but definitely not something like `classA:last-child`  `<Optional>`
4. Expects browser env with global tryToFindApp. SHould allow both root DOMNode and class component ref.
5. Component objects or instances can't be used for searching. Only names are supported
6. No proper types present for others, who will try to access the output. `<Optional>`

Optional marked items are good to have and can be build on top, but other things can be blocker for some usecases and can't be solved in userland.

**Comment by christian-bromann** [comment]
@bendtherules I think these are all great features that can find their place in this library. We appreciate every pull request. Cheers!

**Comment by baruchvlz** [comment]
Hi @bendtherules, thanks for your interest in the library.
As your other points: 

1. Copying the FiberNode into the return value can cause some issues with performance when testing big applications as the FiberNodes will also have the FiberNode of the parent and children hierarchies of the component. You can indeed chain the search, but it's a bit tricky:

```
const myCmp = resq('MyComponent', document.querySelector('#root');
const otherComp = resq('OtherComp', myCmp.node);
```

But we are aware that this can, and has, to be done in a better way. Maybe you can help us with this (:.

2. CSS selectors will not be a part of this library as it defeats the purpose, most testing frameworks that use this library, WebdriverIO for example, already provide a way to use CSS selectors. You can always use the component node(s) to do CSS selectors via `querySelector`, `querySelectorAll`, etc.

3. The browser env global is optional for when you want to do searches asynchronously. You can, however, do synchronous queries. It was added [here](https://github.com/baruchvlz/resq/pull/32/files) but I missed the documentation update. Essentially you can do soemthing like:

```
resq('MyComponent', document.getElementById('root');
```

4 & 5. Not really sure what you mean by these two points. Maybe you can explain further.

**Comment by bendtherules** [comment]
To give context about most of the suggestions, my understanding is that resq always eagerly converts back results into a simplified structure - which has no information about the FiberNode structure.
It maps back stuff to DOM nodes, if available.

My suggestion is that (allow as a option or by default) return results containing reference to underlying FiberNode. This will allow user to do further operation on the results till they reach the final node they are interested in. When they have the final node, that should ideally be converted to a simplified structure (like what resq returns currently) so that it can be stored, serialized easily without memory leak.
In short, currently resq returns stuff that is great if it is the final step, but is a very poor choice if user needs it as an intermediate step. It doesn't contain enough information for further processing.

@baruchvlz  To explain from your response:

1. The structure is great if it's the end step (with the benefits you mentioned), but what if it's only an intermediate step for the user??
Also, that code snippet will not work if the child of a component is also another component. Example: https://stackblitz.com/edit/resq-hagoke (it finds global button in chained case, not the inner button as expected)

2. It is not about CSS selectors on the DOM node/tree. Its is about using selectors on the react component tree. 
For eg. in `<A><B/><B/></A>`, how can I select the second nested B reliably and easily? What if I could just write `resq$('A B:last-child')` instead? Something like https://www.npmjs.com/package/snabbdom-selector for react tree.

3. This is somewhat better what you showed. But it still doesn't allow root component refs. Like
```js
const rootRef = React.createRef<React.Component>();
ReactDOM.render(<SomeComponentClass ref={rootRef} />, something);

resq$('selector', rootRef);
```
If this was supported, getting access to react internals will be simplified for this library (as there is no need to search stuff in dom node, this ref contains the exact same object we find there) and effectively, we wouldn't need to even expect that any DOM exists.

4. resq only allows searching by component name. What happens if two components have same name (or names get mangled in prod)?
What if you could search by Component (class or function) itself instead of their name? Like `resq$(SomeComponentClass)` where `SomeComponentClass` extends `React.Component`. We can just match with `node.type` instead of name.
In extension, for class components you can also search them by component instance ref.

5. Just that having some proper doc or type definition for the output object would be nice. What all things can be null, when are they null, etc. Not that important though.

**Comment by baruchvlz** [comment]
> My suggestion is that (allow as a option or by default) return results containing reference to underlying FiberNode. 

This is something we could add. But not as a default, rather as a flag to the functions.

> What if I could just write resq$('A B:last-child') 

I like this. Using CSS like pseudo-selectors to pick the elements will be really helpful.

```
<A>
  <B />
  <B />
  <B />
</A>


resq$('A B:nth(1)')
resq$('A B:last-child)')
resq$('A B:first-child')
```

> resq only allows searching by component name. What happens if two components have same name (or names get mangled in prod)?

If the names get mangled there will be no actual way of finding the component via the "pre-mangled" name since it won't exist in the code. The library is meant to be used along side testing frameworks and in my opinion you really shouldn't be testing an application in production.

> What if you could search by Component (class or function) itself instead of their name? Like resq$(SomeComponentClass) where SomeComponentClass extends React.Component. We can just match with node.type instead of name.

This is basically what the library does. React sets the `type` property of the FiberNode as a function so you have access to the function's `name` property (which would be the name of the component either a class or a function). In the case of an anonymous component then the library wouldn't work (this also happens in the React DevTools, but they use `_default` as the name for anonymous functions.

>  But it still doesn't allow root component refs.

The library isn't meant to be used along side a React application but rather to be used in a browser and there we don't have access to `ref`s.

However, this is a good idea since it could potentially allow the library to be used inside a React application, **but** if we decide to introduce this we will have to consider performance thresholds for when the library is used in a big production. Thoughts on this @christian-bromann ?

**Comment by bendtherules** [comment]
For all the 3 disagreements, the question is whether to allow (optionally) debugging/testing with help from the main React application?
Ofcourse, I don't expect this test code to be shipped **with** the application for end users, but more like conditionally loaded for developers (in production). Why is this a bad idea?

Imagine asking the same questions about React debugger. 
1. What if React debugger didn't at all work in production? Not just be less useful in prod, but not work at all. 
Same question here, with name mangling (which usually doesn't make component names unique globally) resq effectively is of no use currently in prod. If you could find by the component itself (instead of name), that would work in prod.
2. Why can't test code be optionally loaded for developers in prod, just like React debugger extension? It wouldn't affect perf for end users, just be more helpful for developers. If anything, testing should be more important on prod version.

In general, my suggestions are also about considering widening the scope of this library. Why shouldn't you be able to write some simple (developer) tools for React application with this (say, if it had more helpers like traversal api)?

I understand that all this is probably asking for too much and it is useful as it is for testing, but from my viewpoint this lib stands at a sweet point (being the only working lib which can traverse React fiber nodes). Hence, all these suggestions.

**Comment by baruchvlz** [comment]
Closing this as stale. There are some good suggestions that I will take a look at for v2.
