### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by christian-bromann** [baruchvlz/resq#5]
Hey @baruchvlz ,

thanks for working on this! I looked the code and wanted to share some idea. Maybe I get the time to contribute to this project and make PRs for them.

- in `index.js` - `await waitToLoadReact(5000)`: maybe we can make the timeout configurable but 5000ms seams a reasonable default
- in `getRootComponent` - do all root elements have the id `'#root'`?
- instead of expecting the root component to have the id `root` we could let `waitToLoadReact` return the root element because it will look for it anyway, no?
- to make this usable in WebdriverIO it will be necessary that this page bundles the entrypoint into a single (minfied) file so I can inject it into the page and use it afterwards

**Comment by baruchvlz** [comment]
- Yea, I'll add an optional parameter for timeout
- Good point, that's not guaranteed to be `#root`, this is just the one `create-react-app` uses. I'll adjust the search to something more dynamic that way we can also use it for apps with handlers (ie SSR)
- That's a good point, once I change the search for the root component, I'll have `waitToLoadReact` to return it
- Sure, I'll publish the package as a bundle.

**Comment by baruchvlz** [comment]
Publishing the library as a bundle has been a pain in the ass. It was working for `create-react-app`s but for custom built apps it was failing.

I'm hoping this https://github.com/baruchvlz/resq/commit/228038eaddd25b20332da9e29899ecb815659d8d fixes the issue. I tested it locally and it seems to be fine.
