### ISSUE TITLE
IE11 not identifying elements properly

### ISSUE THREAD

**Issue by abhinaba-ghosh** [baruchvlz/resq#51]
Hi,

I was playing with resq and I have encountered functional differences in different browser. Chrome and Firefox greatly handles the react component identification part. But, not IE11.

I have changed res$$ to resqTT, as IE can't handle those symbols. But, this is not a showstopper. 

I have attached the findings for two different browsers for same website:

website under test: https://react-shopping-cart-67954.firebaseapp.com/

**Chrome:**

![image](https://user-images.githubusercontent.com/23141842/68920230-a69ebb80-079a-11ea-83fe-81ef601f8dea.png)

you can clearly see that I am getting the element and element count is 1

***IE11:**

![image](https://user-images.githubusercontent.com/23141842/68920290-cafa9800-079a-11ea-9390-70dbe8054929.png)

Now, element size is 0

Any help to mitigate this issue will be a great help. I need to run resq in IE anyway.

**Comment by baruchvlz** [comment]
Hey @abhinaba1080 sorry for the late response. This is an interesting issue indeed, have you found a way around it? It is hard for me to work on this as I don't own a Windows machine.

**Comment by abhinaba1080** [comment]
i did not get any solution around it. This library is actually fantastic, but without IE support, it hard to leverage this library. 

you can use a virtual windows machine for the time being. you will be the best person to analyse thia issue as you know the whereabouts.

**Comment by abhinaba1080** [comment]
@mvasin as this #53 is merged , in which version i can exect the fix? can i get the transpiled js ?

**Comment by mvasin** [comment]
Hi @abhinaba1080, it’s it 1.7.1

**Comment by mvasin** [comment]
Please let us know if #53 made any difference for you.

**Comment by abhinaba1080** [comment]
I have used the latest. Isue still there. IE is showing really wired behavior as couple of cases IE finding out the element correct, but failing for other cases. Here are some screenshots:

**Actual Component**

![image](https://user-images.githubusercontent.com/23141842/75244107-2b18c580-57f1-11ea-9169-e1a6c90b8b49.png)


**In Chrome, Element getting identified properly**

![image](https://user-images.githubusercontent.com/23141842/75244147-45eb3a00-57f1-11ea-929d-656c18310a15.png)


**in IE, it is not getting identified:**

![image](https://user-images.githubusercontent.com/23141842/75244191-61564500-57f1-11ea-80b2-826768e65435.png)
