### ISSUE TITLE
Not able to identify RESQ nodes for non-root element

### ISSUE THREAD

**Issue by abhinaba-ghosh** [baruchvlz/resq#60]
RESQ version: 1.8.0

If root is used while fetching the resq nodes, it is able to identify the child elements. But, if non-root element is used, it is failing to identify the same. The attached screenshots will be more descriptive:

DOM:
<img width="284" alt="Screenshot 2020-09-21 at 6 24 17 PM" src="https://user-images.githubusercontent.com/23141842/93768867-adf2e900-fc37-11ea-9c30-c4a14c891647.png">

Fetch Commands:
<img width="589" alt="Screenshot 2020-09-21 at 6 19 23 PM" src="https://user-images.githubusercontent.com/23141842/93768804-8d2a9380-fc37-11ea-9d55-9572b97f08cd.png">
So, in first command it is not able to identify the child elements. Once the root is used, both the child products got identified.

**Comment by baruchvlz** [comment]
Hey @abhinaba-ghosh thanks for reporting this. Do you know if this happened in 1.7.1 as well?

**Comment by abhinaba-ghosh** [comment]
hi @baruchvlz , yes, it is happening with `v1.7.1` too. I am seeing this is happening if a component is getting mounted asynchronously. But it is still wired.

**Comment by abhinaba-ghosh** [comment]
If you need exact use case with a sample `cypress` repo, I can provide the same.

**Comment by baruchvlz** [comment]
I'll take a look at this. Again, thanks for reporting.

**Comment by abhinaba-ghosh** [comment]
Hi @baruchvlz , sorry for pushing this in your busy schedule, but having an update about this issue would be pretty helpful.

**Comment by baruchvlz** [comment]
Hi @abhinaba-ghosh, I was trying to create a reproducible example for this, but was not able to.

I used this example:

```jsx
import React from 'react';

import { resq$, resq$$ } from 'resq';

const Product = ({ text }) => (
  <div className="product">{text}</div>
);

const Container = () => (
  <div className="container">
    {
      ['Foo', 'Bar'].map((text, index) => <Product key={`${index}_${text}`} text={`${index}_${text}`} />)
    }
  </div>
)

function App() {

  React.useEffect(() => {
    window.$ = resq$;
    window.$$ = resq$$
  }, []);

  return (
    <>
      <Container />
    </>
  );
}

export default App;
```

![image](https://user-images.githubusercontent.com/14321495/95680032-c7ec6f80-0bd6-11eb-9526-b6a9d5f51d4a.png)

As you can see in the image, i am able to retrieve both `<Product />` components using the result from `querySelector` as well as the node from the result of using `$('Container', root)`.

**Comment by abhinaba-ghosh** [comment]
Hi Thanks for re-confirming. I will try with the v1.9.0. If still exists, I will share the codebase.

**Comment by abhinaba-ghosh** [comment]
Hi @baruchvlz , some wired behavior after migrating to `v1.9.0`, `byProps` returning multiple nodes which is not the case with the earlier version. You can try out with [this app](https://ahfarmer.github.io/calculator/).

<img width="1194" alt="Screenshot 2020-10-11 at 9 26 08 PM" src="https://user-images.githubusercontent.com/23141842/95683420-b58b2980-0c08-11eb-8d03-ab2fca34dd56.png">

**Comment by baruchvlz** [comment]
@abhinaba-ghosh Thanks for taking a look at v1.9.0. I'm not entirely sure why this is happening, but I tried out your last reported error with both sync and async approaches and could not reproduce.

**Sync**
<img width="1575" alt="Screenshot 2020-10-12 at 08 57 43" src="https://user-images.githubusercontent.com/14321495/95714939-4bef3780-0c69-11eb-8efa-8ef224341a55.png">

**Async**
<img width="1576" alt="Screenshot 2020-10-12 at 08 59 10" src="https://user-images.githubusercontent.com/14321495/95714954-53164580-0c69-11eb-9a27-c05a59bc831e.png">


If you want to have a chat about this, feel free to reach out on Gitter.

**Comment by abhinaba-ghosh** [comment]
working well in the latest version.
