### ISSUE TITLE
Instance of react not found in confined DOM

### ISSUE THREAD

**Issue by abhinaba-ghosh** [baruchvlz/resq#73]
Hi @baruchvlz 

When I am trying to access a component in a specified DOM space, often getting this error. Note, `waitForReact` is completed successfully. 

The repository where you can reproduce this bug: 
https://github.com/abhinaba-ghosh/cypress-react-chain-queries

Resq version: 1.9.2
Platform: Catalina [10.15.7]

Screenshot:
<img width="1195" alt="Screenshot 2020-11-15 at 6 16 08 PM" src="https://user-images.githubusercontent.com/23141842/99185394-99325d80-276f-11eb-8106-cb78236cd442.png">

**Comment by abhinaba-ghosh** [comment]
Even this is not working:
<img width="1180" alt="Screenshot 2020-11-15 at 6 35 01 PM" src="https://user-images.githubusercontent.com/23141842/99185682-730dbd00-2771-11eb-80d9-0ccbe1a4509b.png">

**Comment by baruchvlz** [comment]
It seems like React has changed the property name in the element in React 17. From `__reactInternalInstance` to `__reactFiber`.


As to your issue where chaining react selectors throws an error, well, that's inteded:

```js
resq$('MyComponent').resq$('ChildComponent'`);
```

This doesn't work, what you have to do if you want to support this on your library is to do `resq.waitToLoadReact` on every call of your method. This is an [example from WebdriverIO](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/react%24.js#L47).
