### ISSUE TITLE
resq queries should consider the HTMLElement (node) objects rather RESQ objects

### ISSUE THREAD

**Issue by abhinaba-ghosh** [baruchvlz/resq#76]
Hi @baruchvlz 

**The JSX:**

```js
import React from 'react';
import { getProducts } from '../products';

class AProduct extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      myName: props.name,
      orderCount: 0,
    };
  }

  order() {
    this.setState({
      orderCount: this.state.orderCount + 1,
    });
  }

  render() {
    return (
      <div className="product">
        <span className="name">{this.state.myName}</span>
        <span className="ordered">{this.state.orderCount}</span>
        <button className="order" onClick={this.order.bind(this)}>
          Order
        </button>
      </div>
    );
  }
}

const Products = ({ products }) => (
  <React.Fragment>
    {products.map((product) => (
      <AProduct key={product.id} name={product.name} value="product" />
    ))}
  </React.Fragment>
);

class ProductsContainer extends React.Component {
  state = {
    products: [],
  };

  componentDidMount() {
    // for now use promises
    return getProducts().then((products) => {
      this.setState({
        products,
      });
    });
  }

  render() {
    return (
      <div className="product-container">
        <Products products={this.state.products} />
      </div>
    );
  }
}

export default ProductsContainer;

```

**FETCH Products:**

```js
export const getProducts = () => {
  console.log('fetch products');
  return fetch('http://myapi.com/products')
    .then((r) => r.json())
    .then((json) => {
      console.log('products', json.products);
      return json.products;
    });
};

```

The outcome:

<img width="1303" alt="Screenshot 2020-11-20 at 2 28 59 PM" src="https://user-images.githubusercontent.com/23141842/99780710-dbc3b380-2b3c-11eb-93c1-80c3929d98ad.png">

**Expectation:**
As per (Type definition)[https://github.com/baruchvlz/resq#type-definition], `node` returns the real HTMLElement so `resq$ /resq$$` should consider the `node` rather than the RESQ object

Now, surprisingly, for[ a different react example](https://github.com/abhinaba-ghosh/cypress-react-chain-queries), everything works as expected. 

<img width="604" alt="Screenshot 2020-11-20 at 2 35 33 PM" src="https://user-images.githubusercontent.com/23141842/99781451-e3d02300-2b3d-11eb-9764-77ebbd6faaf1.png">

So, what's really happening for the above example that RESQ is behaving differently?

**Comment by baruchvlz** [comment]
The library is not behaving differently, the value that you're passing the wrong second argument.

In your example `product[0]` is not a HTML element, it's the RESQ object, which means that [the condition to check for HTML element fails](https://github.com/baruchvlz/resq/blob/master/index.js#L12), since the condition doesn't pass, then the library uses the root React element.

As to your suggestion to consider the `node` element, yea sure that would work in your scenario but in the scenario in which the user passes an actual HTML element and not a RESQ node, the library will error. 

Alternatively, there could be a check to see if there's a `node` property and use that instead, etc. But for me that's not really a priority. There are many ways to gather a HTML element and it's an easier API to just expect a HTML element to have been passed.

**Comment by baruchvlz** [comment]
I redacted my last message cause I misunderstood the problem. This does seem like a bug and weird behaviour, I wonder if it's related to React 17. I will investigate this over the weekend.

**Comment by abhinaba-ghosh** [comment]
Hi @baruchvlz , is there any update for the ticket?

**Comment by baruchvlz** [comment]
Hey @abhinaba-ghosh , I currently do not have the time to look into this issue. Sorry for the inconvenience.

**Comment by abhinaba-ghosh** [comment]
Hi @baruchvlz according to [this](https://github.com/abhinaba-ghosh/cypress-react-selector/issues/41#issuecomment-752225576), the issue still observed in React 16

**Comment by baruchvlz** [comment]
Yea, that's my bad I meant to ask about React 17, sorry.

I have a bit more time in the coming weeks, I'll take a look at this again.

**Comment by abhinaba-ghosh** [comment]
@baruchvlz This happens with React 17 too. Do you have an update on this?

**Comment by abhinaba-ghosh** [comment]
Hey @baruchvlz why this is closed? Let me know if this is solved.

**Comment by baruchvlz** [comment]
It's not solved. This ticket has been opened for a while and has gained no traction. I'm not the only one that can write code and I don't have the time to debug the library.

**Comment by abhinaba-ghosh** [comment]
I can understand that. But still this is not the proper justification of closing the issue. Let it be opened until a decision made for this.
