### ISSUE TITLE
Line 9 of src/waitToLoadReact.js throws an error in IE11 because whatToShow and filter aren't optional

### ISSUE THREAD

**Issue by danieltroger** [baruchvlz/resq#77]
The error message is this: `TypeError: Argument not optional`

The "problem" (for IE11) is that createTreeWalker is called with only one argument.

The error is here: https://github.com/baruchvlz/resq/blob/59c4c511efaed1ffd1b7de27f613ece1d3b1bd13/src/waitToLoadReact.js#L9

The documentation proving my point: https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker

![Screen Shot 2020-12-01 at 21 20 30](https://user-images.githubusercontent.com/4047180/100792625-33a2ca00-341b-11eb-889a-2852b64281b8.jpg)

**Comment by baruchvlz** [comment]
Hey @danieltroger thanks for reporting this issue, currently I don't have the time to look into this but PRs are always welcome.
