### ISSUE TITLE
Doesn't work with `displayName` of functional components

### ISSUE THREAD

**Issue by jens-duttke** [baruchvlz/resq#78]
To be able to see the "real" component names in the compiled version of my webapp (https://hexed.it) I'm using `displayName`, like here:
```
export const GridItem: React.FunctionComponent<GridItemProps> = (props) => {
	// [...]   
};

GridItem.displayName = 'GridItem';
```

While the ReactDevTools is showning the `displayName` of the component correctly, `resq` is returning the compiled 1-letter-`name`.
If I change the `getElementName()` function:
https://github.com/baruchvlz/resq/blob/465ab5e3361da40f1b2752e15134cf9304efd972/src/utils.js#L16
to something like:
```js
return isFunction(type) ? (type.displayName || type.name) : type
```
it works fine.

**Comment by baruchvlz** [comment]
PRs are always welcome.

**Comment by jens-duttke** [comment]
> PRs are always welcome.

I can provide a PR for this single line. But I'm not sure about the tests, since they seem to rely on React's internals (Virtual DOM) and I'm not sure if I can address all circumstances.

**Comment by baruchvlz** [comment]
You can add a new tree, based off the ones already there, to the [mock](https://github.com/baruchvlz/resq/blob/master/tests/__mocks__/vdom.js) file but instead of `type` it has `displayName`. Maybe that would cover it.

**Comment by baruchvlz** [comment]
Fair point, let's do this: post a screen recording of a manual test in the PR and I'll also do a manual test and if it all works we can merge it.

**Comment by jens-duttke** [comment]
@baruchvlz: Any chance to get my pull request merged soon?

**Comment by baruchvlz** [comment]
I'll do a release later today after I'm done with work.

**Comment by baruchvlz** [comment]
Haven't been able to do a release yet. Sorry about this, I'll try to do one this week if I'm able to.
