### ISSUE TITLE
Function waitToLoadReact is resolving when global.rootReactElement is undefined

### ISSUE THREAD

**Issue by bkirova** [baruchvlz/resq#82]
The function `waitToLoadReact` is resolving even when the `global.rootReactElement` is undefined instead of retrying till the timeout.
https://github.com/baruchvlz/resq/blob/master/src/waitToLoadReact.js

![tempsnip](https://user-images.githubusercontent.com/17831711/140314376-f9a90870-7ec7-4e78-b075-4da84f2c13f5.png)

Even when the `findReactInstance` function returns undefined the promise is resolved.

This issue is provoking https://github.com/abhinaba-ghosh/cypress-react-selector/issues/104 in the  [cypress-react-selector](https://github.com/abhinaba-ghosh/cypress-react-selector) module.

In our case we have a next.js project.

Repro steps would be just:

```
cy.visit("/")
cy.waitForReact(1000, `#__next`);
cy.react("Logo"); // Some dummy component mounted in the index page
```

The bug is reproducible 1 of 10 times in a run of total 100 tests(we just generate the above test 100 times to repro the bug).

**Comment by baruchvlz** [comment]
Closing assuming it's resolved in #83 .
